# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'NNWebView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NNWebView
 
pod 'NJKWebViewProgress'
pod 'WebViewJavascriptBridge'
  target 'NNWebViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NNWebViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
